AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'EC2 EventBridge thing

  '
Metadata:
  AWS::ServerlessRepo::Application:
    Name: ec2-thing
    Description: An ec2 thing
    Author: Observe Inc
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-1d9p458evhgwf/4807cb4792f21dcb568ec12ab3faa7ed
    HomePageUrl: https://github.com/observeinc/aws-sam-testing
    SemanticVersion: '0.1.0'
    SourceCodeUrl: https://github.com/observeinc/aws-sam-testing
Globals:
  Function:
    Timeout: 20
    MemorySize: 128
Resources:
  Function:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-1d9p458evhgwf/22400a3296b0cc05e20720ec29d15daf
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
      - x86_64
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
              - aws.ec2
              detail-type:
              - EC2 Instance State-change Notification
Outputs:
  Function:
    Description: Lambda Function ARN
    Value:
      Fn::GetAtt:
      - Function
      - Arn
  FunctionIamRole:
    Description: Implicit IAM Role created for function
    Value:
      Fn::GetAtt:
      - FunctionRole
      - Arn
