AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Hello world.

Metadata:
  AWS::ServerlessRepo::Application:
    Name: group 
    Description: A group of applications
    Author: Observe Inc
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    HomePageUrl: https://github.com/observeinc/aws-sam-testing
    SemanticVersion: 0.0.3
    SourceCodeUrl: https://github.com/observeinc/aws-sam-testing


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Parameters:
  EnableEC2:
    Type: String
    Default: false
    Description: >-
      Enable EC2 stack
    AllowedValues:
      - true
      - false
  Verbosity:
    Type: Number
    Default: 3
    Description: >-
      Logging verbosity.
  TrailEnableLogFileValidation:
    Type: String
    Default: false
    Description: Indicates whether CloudTrail validates the integrity of log files.
    AllowedValues:
      - true
      - false
  TrailIncludeGlobalEvents:
    Type: String
    Default: true
    Description: >-
      Indicates whether the trail is publishing events from global services,
      such as IAM, to the log files.
    AllowedValues:
      - true
      - false
  TrailEnabled:
    Type: String
    Default: true
    Description: >-
      Whether to collect CloudTrail data or not. Only disable if you already submit Cloudtrail data separately.
    AllowedValues:
      - true
      - false
  TrailMultiRegion:
     Type: String
     Default: false
     Description: >-
       Indicates whether the CloudTrail trail is created in the region in which
       you create the stack (false) or in all regions (true).
     AllowedValues:
      - true
      - false
  TrailExcludeManagementEventSources:
    Type: CommaDelimitedList
    Default:  "kms.amazonaws.com,rdsdata.amazonaws.com"
    Description: >-
      A comma-separated list of Management Event Sources to exclude.

      See the following link for more info:
      https://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-management-events-with-cloudtrail.html


Conditions:
  EC2IsEnabled: !Equals
     - Ref: EnableEC2
     - true
 
Resources:
  HelloWorld:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-west-2:739672403694:applications/hello-world-thing
        SemanticVersion: 0.0.1
  EC2:
    Type: AWS::Serverless::Application
    Condition: EC2IsEnabled
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-west-2:739672403694:applications/ec2-thing
        SemanticVersion: 0.1.0

