name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Setup AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-west-2

    - name: github pre-release
      id: prerelease
      if: github.event_name == 'push'
      uses: ahmadnassri/action-semantic-release@v2
      with:
        config: ${{ github.workspace }}/.releaserc.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: github full release
      id: fullrelease
      if: github.event_name == 'workflow_dispatch'
      uses: ahmadnassri/action-semantic-release@v2
      with:
        config: ${{ github.workspace }}/.releaserc-release.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: aws sam release
      run: |
        echo "VERSION=${{ steps.prerelease.outputs.release-version }}" >> $GITHUB_ENV
        make sam-package-all-regions
